# Generated by Django 5.0 on 2024-02-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='holiday_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
