# Generated by Django 5.0 on 2023-12-31 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0002_rawsignings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('monday', models.FloatField(default=0.0)),
                ('tuesday', models.FloatField(default=0.0)),
                ('wednesday', models.FloatField(default=0.0)),
                ('thursday', models.FloatField(default=0.0)),
                ('friday', models.FloatField(default=0.0)),
                ('saturday', models.FloatField(default=0.0)),
                ('sunday', models.FloatField(default=0.0)),
                ('ordinary_hours', models.FloatField(default=0.0)),
                ('daytime_overtime', models.FloatField(default=0.0)),
                ('night_surcharge_hours', models.FloatField(default=0.0)),
                ('night_overtime', models.FloatField(default=0.0)),
                ('holiday_hours', models.FloatField(default=0.0)),
                ('night_holiday_hours', models.FloatField(default=0.0)),
                ('daytime_holiday_overtime', models.FloatField(default=0.0)),
                ('night_holiday_overtime', models.FloatField(default=0.0)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.worker')),
            ],
        ),
    ]
