# Generated by Django 5.0 on 2024-01-02 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0001_initial'),
        ('workers', '0002_rawsignings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settlement',
            name='daytime_holiday_overtime',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='daytime_overtime',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='holiday_hours',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='night_holiday_hours',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='night_holiday_overtime',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='night_overtime',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='night_surcharge_hours',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='ordinary_hours',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='wednesday',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='worker',
        ),
        migrations.AddField(
            model_name='settlement',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SettlementDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.FloatField(default=0.0)),
                ('tuesday', models.FloatField(default=0.0)),
                ('wednesday', models.FloatField(default=0.0)),
                ('thursday', models.FloatField(default=0.0)),
                ('friday', models.FloatField(default=0.0)),
                ('saturday', models.FloatField(default=0.0)),
                ('sunday', models.FloatField(default=0.0)),
                ('ordinary_hours', models.FloatField(default=0.0)),
                ('daytime_overtime', models.FloatField(default=0.0)),
                ('night_surcharge_hours', models.FloatField(default=0.0)),
                ('night_overtime', models.FloatField(default=0.0)),
                ('holiday_hours', models.FloatField(default=0.0)),
                ('night_holiday_hours', models.FloatField(default=0.0)),
                ('daytime_holiday_overtime', models.FloatField(default=0.0)),
                ('night_holiday_overtime', models.FloatField(default=0.0)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settlement.settlement')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.worker')),
            ],
        ),
    ]
