# Generated by Django 5.0 on 2024-01-04 05:47

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0002_remove_settlement_daytime_holiday_overtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementdetails',
            name='working_shifts',
            field=models.JSONField(default=None, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
