# Generated by Django 5.0 on 2024-01-09 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0004_alter_settlementdetails_working_shifts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settlementdetails',
            options={'verbose_name_plural': 'Settlement details'},
        ),
    ]
