# Generated by Django 5.0 on 2024-01-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0005_alter_settlementdetails_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementdetails',
            name='total_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
