# Generated by Django 5.0 on 2024-03-06 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0006_settlementdetails_total_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlementdetails',
            name='settlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='settlement.settlement'),
        ),
    ]
