# Generated by Django 5.0 on 2024-03-09 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settlement', '0007_alter_settlementdetails_settlement'),
        ('workers', '0005_alter_rawsignings_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_date', models.DateField()),
                ('settlement', models.ManyToManyField(to='settlement.settlement')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours', models.FloatField(default=0.0)),
                ('ordinary_hours', models.FloatField(default=0.0)),
                ('daytime_overtime', models.FloatField(default=0.0)),
                ('night_surcharge_hours', models.FloatField(default=0.0)),
                ('night_overtime', models.FloatField(default=0.0)),
                ('holiday_hours', models.FloatField(default=0.0)),
                ('night_holiday_hours', models.FloatField(default=0.0)),
                ('daytime_holiday_overtime', models.FloatField(default=0.0)),
                ('night_holiday_overtime', models.FloatField(default=0.0)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='payroll.payroll')),
                ('settlement_detail', models.ManyToManyField(to='settlement.settlementdetails')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.worker')),
            ],
        ),
    ]
