# Generated by Django 5.0 on 2024-04-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
        ('settlement', '0007_alter_settlementdetails_settlement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='settlement',
            field=models.ManyToManyField(related_name='payroll', to='settlement.settlement'),
        ),
    ]
