# Generated by Django 5.0 on 2023-12-31 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawSignings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_number', models.PositiveBigIntegerField()),
                ('date_signed', models.DateTimeField()),
                ('signed_type', models.CharField(choices=[('E', 'Entrada'), ('S', 'Salida')], max_length=1)),
                ('door', models.CharField(max_length=30)),
                ('contract_number', models.CharField(max_length=30)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.worker')),
            ],
        ),
    ]
