# Generated by Django 5.0 on 2024-01-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_rawsignings'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawsignings',
            name='normalized_date_signed',
            field=models.DateTimeField(null=True),
        ),
    ]
