# Generated by Django 5.0 on 2024-03-06 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_alter_rawsignings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawsignings',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signings', to='workers.worker'),
        ),
    ]
